// <auto-generated />
using System;
using BookingForm.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingForm.Migrations
{
    [DbContext(typeof(BookingFormContext))]
    [Migration("20181016052734_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookingForm.Models.Appoinment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Borrow")
                        .IsRequired();

                    b.Property<string>("Cmnd")
                        .IsRequired();

                    b.Property<string>("Customer")
                        .IsRequired();

                    b.Property<DateTime>("Day");

                    b.Property<string>("Details")
                        .IsRequired();

                    b.Property<DateTime>("Due");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("Job")
                        .IsRequired();

                    b.Property<string>("MeetingAddress")
                        .IsRequired();

                    b.Property<string>("MeetingDay")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("Place")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.Property<string>("Product")
                        .IsRequired();

                    b.Property<string>("Purpose")
                        .IsRequired();

                    b.Property<string>("Requires")
                        .IsRequired();

                    b.Property<string>("WorkPlace")
                        .IsRequired();

                    b.Property<DateTime>("fromTime");

                    b.Property<DateTime>("toTime");

                    b.HasKey("ID");

                    b.ToTable("appoinment");
                });
#pragma warning restore 612, 618
        }
    }
}
